enum {
   ESTEREOTIPO_CLASSES,
   ESTEREOTIPO_RELACOES,
   RESERVADAS,
   SIMBOLOS,
   CONVENCAO_CLASSES,
   CONVENCAO_RELACOES,
   CONVENCAO_INSTANCIAS,
   DADOS_NATIVOS,
   NOVOS_TIPOS,
   META_ATRIBUTOS
} ;