enum {
   ESTEREOTIPO_CLASSES,
   ESTEREOTIPO_RELACOES,
   RESERVADAS,
   SIMBOLOS,
   CONVENCAO_IDENTIFICADOR,
   CONVENCAO_RELACOES,
   CONVENCAO_INSTANCIAS,
   TIPOS_NATIVOS,
   NOVOS_TIPOS,
   META_ATRIBUTOS
} ;